
do:
	javac YoutubeExtractor.java -cp jsoup-1.7.1.jar:commons-lang3-3.1.jar 

run:
	java -classpath ./jsoup-1.7.1.jar:./commons-lang3-3.1.jar:. YoutubeExtractor "Tom Lehrer"
	xsltproc youtube.xslt youtube.xml >& FOO.html
